spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  application:
    name: venda
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    registerWithEureka: true
server:
  port: 8080