spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: arquitetura
      username: adm
      password: 123
      authentication-database: admin
      uri: mongodb://adm:123@localhost:27017/
  application:
    name: cliente
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    registerWithEureka: true
server:
  port: 0
